#!/bin/sh
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 10/" /etc/pacman.conf
pacman --noconfirm -Sy archlinux-keyring
pacman-key --init

cfdisk /dev/nvme0n1

boot="/dev/nvme0n1p5"
swap="/dev/nvme0n1p6"
root="/dev/nvme0n1p7"

clear
mkfs.ext4 "$root"
mkswap "$swap"
swapon "$swap"
mkfs.fat -F32 "$boot"
mount "$root" /mnt
mkdir -p /mnt/boot/efi 
mount "$boot" /mnt/boot/efi
pacstrap /mnt base base-devel linux linux-firmware sudo sed
genfstab -U /mnt >> /mnt/etc/fstab
sed '1,/^#part2$/d' `basename $0` > /mnt/archinstall2.sh
chmod +x /mnt/archinstall2.sh
arch-chroot /mnt ./archinstall2.sh
exit

#part2
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 10/" /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "arch" >> /etc/hostname

# Baixando e instalando GRUB
pacman --noconfirm -S grub efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"/GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.ppfeaturemask=0xffffffff loglevel=3 quiet"/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

pacman --noconfirm -Sy bluez bluez-utils pulseaudio-bluetooth networkmanager \
        btop qbittorrent nicotine+ firefox gimp obsidian \
        git rsync yt-dlp bc ffmpegthumbnailer neovim \
         cmus zathura zathura-pdf-mupdf unrar mpv \
        pulseaudio pulsemixer polkit xclip xwallpaper ufw imagemagick \
        man zsh nsxiv upower tmux fzf dunst nodejs aria2 clipmenu \
        xorg xorg-xinit dmenu unzip python-pip lf mediainfo libbsd \
	    noto-fonts-cjk noto-fonts-emoji noto-fonts libertinus-font perl-image-exiftool npm jq file-roller \
	    p7zip zsh-syntax-highlighting zsh-autosuggestions pass openssh texlive code progress linux-headers discord
systemctl enable NetworkManager 
systemctl enable bluetooth 

id="$(ls -al /dev/disk/by-uuid/ | awk '/sda$/ {print $9}')"
sudo mkdir -p /mnt/ssd500
echo "UUID="$id"	/mnt/ssd500	ext4	defaults	0	0" >> /etc/fstab

idhd=$(ls -al /dev/disk/by-uuid/ | awk '/sdb1$/ {print $9}')
sudo mkdir -p /mnt/hd3tb
echo "UUID="$idhd"	/mnt/hd3tb	ext4	defaults	0	0" >> /etc/fstab

sed 's/#Experimental = false/Experimental = true/g' /etc/bluetooth/main.conf
sed 's/#KernelExperimental = false/KernelExperimental = true/g' /etc/bluetooth/main.conf

clear
echo "Senha root"
passwd
echo " %wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
read -p "Nome do usuario: " usuario
useradd -mG wheel -s /bin/zsh $usuario
echo "Senha do usuario"
passwd $usuario
ai3_path=/home/$usuario/archinstall3.sh
sed '1,/^#part3$/d' archinstall2.sh > $ai3_path
chown $usuario:$usuario $ai3_path
chmod +x $ai3_path
su -c $ai3_path -s /bin/sh $usuario
exit 

#part3
cd
sudo mount /dev/sda /mnt/ssd500
sudo mount /dev/sdb1 /mnt/hd3tb

cp -r /mnt/hd3tb/backup/.mozilla .
cp -r /mnt/hd3tb/backup/.ssh .
cp -r /mnt/hd3tb/backup/.password-store .

ln -s /mnt/hd3tb .
ln -s /mnt/hd3tb/links/Downloads .
ln -s /mnt/hd3tb/links/Documents .
ln -s /mnt/hd3tb/links/Music .

git clone --separate-git-dir=$HOME/.dotfiles git@github.com:rabpaulo/dots.git temparq
rsync --recursive --exclude '.git' temparq/ $HOME/

cd ~/hd3tb/repos/
cd 'suckless-stuff/dwm/' 
sudo make install
cd '../dwmblocks/'
sudo make install
cd '../st/'
sudo make install
cd '../dmenu/'
sudo make install
cd 

sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si cd $HOME

yay -S cmusfm downgrade gallery-dl-git brave-bin nvim-packer-git ueberzugpp upscayl-bin firefox-nightly-bin
yay -Yc

nvim -c ':PackerSync'

cd 
rm -rf  yay/ .cache temparq/ .dotfiles/ archinstall3.sh suckless-stuff .bash* suckless-stuff

python -m venv venv

exit
